version: 2
jobs:
  build:
    docker:
      # -browsers-legacy gets us PhantomJS (see https://circleci.com/docs/2.0/circleci-images/#language-image-variants)
      - image: circleci/clojure:lein-2.8.1-browsers-legacy

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
        
      # run tests!
      - run: lein test